package ca.willatendo.simplelibrary;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.material.Fluid;

public final class Tags {
    public static final class Blocks {
        public static final TagKey<Block> BARRELS = Tags.Blocks.tag("barrels");
        public static final TagKey<Block> BARRELS_WOODEN = Tags.Blocks.tag("barrels/wooden");
        public static final TagKey<Block> BOOKSHELVES = Tags.Blocks.tag("bookshelves");
        public static final TagKey<Block> BUDDING_BLOCKS = Tags.Blocks.tag("budding_blocks");
        public static final TagKey<Block> BUDS = Tags.Blocks.tag("buds");
        public static final TagKey<Block> CHAINS = Tags.Blocks.tag("chains");
        public static final TagKey<Block> CHESTS = Tags.Blocks.tag("chests");
        public static final TagKey<Block> CHESTS_ENDER = Tags.Blocks.tag("chests/ender");
        public static final TagKey<Block> CHESTS_TRAPPED = Tags.Blocks.tag("chests/trapped");
        public static final TagKey<Block> CHESTS_WOODEN = Tags.Blocks.tag("chests/wooden");
        public static final TagKey<Block> CLUSTERS = Tags.Blocks.tag("clusters");
        public static final TagKey<Block> COBBLESTONES = Tags.Blocks.tag("cobblestones");
        public static final TagKey<Block> COBBLESTONES_NORMAL = Tags.Blocks.tag("cobblestones/normal");
        public static final TagKey<Block> COBBLESTONES_INFESTED = Tags.Blocks.tag("cobblestones/infested");
        public static final TagKey<Block> COBBLESTONES_MOSSY = Tags.Blocks.tag("cobblestones/mossy");
        public static final TagKey<Block> COBBLESTONES_DEEPSLATE = Tags.Blocks.tag("cobblestones/deepslate");
        public static final TagKey<Block> CONCRETES = Tags.Blocks.tag("concretes");
        public static final TagKey<Block> DYED = Tags.Blocks.tag("dyed");
        public static final TagKey<Block> DYED_BLACK = Tags.Blocks.tag("dyed/black");
        public static final TagKey<Block> DYED_BLUE = Tags.Blocks.tag("dyed/blue");
        public static final TagKey<Block> DYED_BROWN = Tags.Blocks.tag("dyed/brown");
        public static final TagKey<Block> DYED_CYAN = Tags.Blocks.tag("dyed/cyan");
        public static final TagKey<Block> DYED_GRAY = Tags.Blocks.tag("dyed/gray");
        public static final TagKey<Block> DYED_GREEN = Tags.Blocks.tag("dyed/green");
        public static final TagKey<Block> DYED_LIGHT_BLUE = Tags.Blocks.tag("dyed/light_blue");
        public static final TagKey<Block> DYED_LIGHT_GRAY = Tags.Blocks.tag("dyed/light_gray");
        public static final TagKey<Block> DYED_LIME = Tags.Blocks.tag("dyed/lime");
        public static final TagKey<Block> DYED_MAGENTA = Tags.Blocks.tag("dyed/magenta");
        public static final TagKey<Block> DYED_ORANGE = Tags.Blocks.tag("dyed/orange");
        public static final TagKey<Block> DYED_PINK = Tags.Blocks.tag("dyed/pink");
        public static final TagKey<Block> DYED_PURPLE = Tags.Blocks.tag("dyed/purple");
        public static final TagKey<Block> DYED_RED = Tags.Blocks.tag("dyed/red");
        public static final TagKey<Block> DYED_WHITE = Tags.Blocks.tag("dyed/white");
        public static final TagKey<Block> DYED_YELLOW = Tags.Blocks.tag("dyed/yellow");
        public static final TagKey<Block> END_STONES = Tags.Blocks.tag("end_stones");
        public static final TagKey<Block> FENCE_GATES = Tags.Blocks.tag("fence_gates");
        public static final TagKey<Block> FENCE_GATES_WOODEN = Tags.Blocks.tag("fence_gates/wooden");
        public static final TagKey<Block> FENCES = Tags.Blocks.tag("fences");
        public static final TagKey<Block> FENCES_NETHER_BRICK = Tags.Blocks.tag("fences/nether_brick");
        public static final TagKey<Block> FENCES_WOODEN = Tags.Blocks.tag("fences/wooden");
        public static final TagKey<Block> FLOWERS_SMALL = Tags.Blocks.tag("flowers/small");
        public static final TagKey<Block> FLOWERS_TALL = Tags.Blocks.tag("flowers/tall");
        public static final TagKey<Block> FLOWERS = Tags.Blocks.tag("flowers");
        public static final TagKey<Block> GLASS_BLOCKS = Tags.Blocks.tag("glass_blocks");
        public static final TagKey<Block> GLASS_BLOCKS_COLORLESS = Tags.Blocks.tag("glass_blocks/colorless");
        public static final TagKey<Block> GLASS_BLOCKS_CHEAP = Tags.Blocks.tag("glass_blocks/cheap");
        public static final TagKey<Block> GLASS_BLOCKS_TINTED = Tags.Blocks.tag("glass_blocks/tinted");
        public static final TagKey<Block> GLASS_PANES = Tags.Blocks.tag("glass_panes");
        public static final TagKey<Block> GLASS_PANES_COLORLESS = Tags.Blocks.tag("glass_panes/colorless");
        public static final TagKey<Block> GLAZED_TERRACOTTAS = Tags.Blocks.tag("glazed_terracottas");
        public static final TagKey<Block> GRAVELS = Tags.Blocks.tag("gravels");
        public static final TagKey<Block> HIDDEN_FROM_RECIPE_VIEWERS = Tags.Blocks.tag("hidden_from_recipe_viewers");
        public static final TagKey<Block> NETHERRACKS = Tags.Blocks.tag("netherracks");
        public static final TagKey<Block> OBSIDIANS = Tags.Blocks.tag("obsidians");
        public static final TagKey<Block> OBSIDIANS_NORMAL = Tags.Blocks.tag("obsidians/normal");
        public static final TagKey<Block> OBSIDIANS_CRYING = Tags.Blocks.tag("obsidians/crying");
        public static final TagKey<Block> ORE_BEARING_GROUND_DEEPSLATE = Tags.Blocks.tag("ore_bearing_ground/deepslate");
        public static final TagKey<Block> ORE_BEARING_GROUND_NETHERRACK = Tags.Blocks.tag("ore_bearing_ground/netherrack");
        public static final TagKey<Block> ORE_BEARING_GROUND_STONE = Tags.Blocks.tag("ore_bearing_ground/stone");
        public static final TagKey<Block> ORE_RATES_DENSE = Tags.Blocks.tag("ore_rates/dense");
        public static final TagKey<Block> ORE_RATES_SINGULAR = Tags.Blocks.tag("ore_rates/singular");
        public static final TagKey<Block> ORE_RATES_SPARSE = Tags.Blocks.tag("ore_rates/sparse");
        public static final TagKey<Block> ORES = Tags.Blocks.tag("ores");
        public static final TagKey<Block> ORES_COAL = Tags.Blocks.tag("ores/coal");
        public static final TagKey<Block> ORES_COPPER = Tags.Blocks.tag("ores/copper");
        public static final TagKey<Block> ORES_DIAMOND = Tags.Blocks.tag("ores/diamond");
        public static final TagKey<Block> ORES_EMERALD = Tags.Blocks.tag("ores/emerald");
        public static final TagKey<Block> ORES_GOLD = Tags.Blocks.tag("ores/gold");
        public static final TagKey<Block> ORES_IRON = Tags.Blocks.tag("ores/iron");
        public static final TagKey<Block> ORES_LAPIS = Tags.Blocks.tag("ores/lapis");
        public static final TagKey<Block> ORES_NETHERITE_SCRAP = Tags.Blocks.tag("ores/netherite_scrap");
        public static final TagKey<Block> ORES_QUARTZ = Tags.Blocks.tag("ores/quartz");
        public static final TagKey<Block> ORES_REDSTONE = Tags.Blocks.tag("ores/redstone");
        public static final TagKey<Block> ORES_IN_GROUND_DEEPSLATE = Tags.Blocks.tag("ores_in_ground/deepslate");
        public static final TagKey<Block> ORES_IN_GROUND_NETHERRACK = Tags.Blocks.tag("ores_in_ground/netherrack");
        public static final TagKey<Block> ORES_IN_GROUND_STONE = Tags.Blocks.tag("ores_in_ground/stone");
        public static final TagKey<Block> PUMPKINS = Tags.Blocks.tag("pumpkins");
        public static final TagKey<Block> PUMPKINS_NORMAL = Tags.Blocks.tag("pumpkins/normal");
        public static final TagKey<Block> PUMPKINS_CARVED = Tags.Blocks.tag("pumpkins/carved");
        public static final TagKey<Block> PUMPKINS_JACK_O_LANTERNS = Tags.Blocks.tag("pumpkins/jack_o_lanterns");
        public static final TagKey<Block> PLAYER_WORKSTATIONS_CRAFTING_TABLES = Tags.Blocks.tag("player_workstations/crafting_tables");
        public static final TagKey<Block> PLAYER_WORKSTATIONS_FURNACES = Tags.Blocks.tag("player_workstations/furnaces");
        public static final TagKey<Block> RELOCATION_NOT_SUPPORTED = Tags.Blocks.tag("relocation_not_supported");
        public static final TagKey<Block> ROPES = Tags.Blocks.tag("ropes");
        public static final TagKey<Block> SANDS = Tags.Blocks.tag("sands");
        public static final TagKey<Block> SANDS_COLORLESS = Tags.Blocks.tag("sands/colorless");
        public static final TagKey<Block> SANDS_RED = Tags.Blocks.tag("sands/red");
        public static final TagKey<Block> SANDSTONE_BLOCKS = Tags.Blocks.tag("sandstone/blocks");
        public static final TagKey<Block> SANDSTONE_SLABS = Tags.Blocks.tag("sandstone/slabs");
        public static final TagKey<Block> SANDSTONE_STAIRS = Tags.Blocks.tag("sandstone/stairs");
        public static final TagKey<Block> SANDSTONE_RED_BLOCKS = Tags.Blocks.tag("sandstone/red_blocks");
        public static final TagKey<Block> SANDSTONE_RED_SLABS = Tags.Blocks.tag("sandstone/red_slabs");
        public static final TagKey<Block> SANDSTONE_RED_STAIRS = Tags.Blocks.tag("sandstone/red_stairs");
        public static final TagKey<Block> SANDSTONE_UNCOLORED_BLOCKS = Tags.Blocks.tag("sandstone/uncolored_blocks");
        public static final TagKey<Block> SANDSTONE_UNCOLORED_SLABS = Tags.Blocks.tag("sandstone/uncolored_slabs");
        public static final TagKey<Block> SANDSTONE_UNCOLORED_STAIRS = Tags.Blocks.tag("sandstone/uncolored_stairs");
        public static final TagKey<Block> SKULLS = Tags.Blocks.tag("skulls");
        public static final TagKey<Block> STONES = Tags.Blocks.tag("stones");
        public static final TagKey<Block> STORAGE_BLOCKS = Tags.Blocks.tag("storage_blocks");
        public static final TagKey<Block> STORAGE_BLOCKS_BONE_MEAL = Tags.Blocks.tag("storage_blocks/bone_meal");
        public static final TagKey<Block> STORAGE_BLOCKS_COAL = Tags.Blocks.tag("storage_blocks/coal");
        public static final TagKey<Block> STORAGE_BLOCKS_COPPER = Tags.Blocks.tag("storage_blocks/copper");
        public static final TagKey<Block> STORAGE_BLOCKS_DIAMOND = Tags.Blocks.tag("storage_blocks/diamond");
        public static final TagKey<Block> STORAGE_BLOCKS_DRIED_KELP = Tags.Blocks.tag("storage_blocks/dried_kelp");
        public static final TagKey<Block> STORAGE_BLOCKS_EMERALD = Tags.Blocks.tag("storage_blocks/emerald");
        public static final TagKey<Block> STORAGE_BLOCKS_GOLD = Tags.Blocks.tag("storage_blocks/gold");
        public static final TagKey<Block> STORAGE_BLOCKS_IRON = Tags.Blocks.tag("storage_blocks/iron");
        public static final TagKey<Block> STORAGE_BLOCKS_LAPIS = Tags.Blocks.tag("storage_blocks/lapis");
        public static final TagKey<Block> STORAGE_BLOCKS_NETHERITE = Tags.Blocks.tag("storage_blocks/netherite");
        public static final TagKey<Block> STORAGE_BLOCKS_RAW_COPPER = Tags.Blocks.tag("storage_blocks/raw_copper");
        public static final TagKey<Block> STORAGE_BLOCKS_RAW_GOLD = Tags.Blocks.tag("storage_blocks/raw_gold");
        public static final TagKey<Block> STORAGE_BLOCKS_RAW_IRON = Tags.Blocks.tag("storage_blocks/raw_iron");
        public static final TagKey<Block> STORAGE_BLOCKS_REDSTONE = Tags.Blocks.tag("storage_blocks/redstone");
        public static final TagKey<Block> STORAGE_BLOCKS_RESIN = Tags.Blocks.tag("storage_blocks/resin");
        public static final TagKey<Block> STORAGE_BLOCKS_SLIME = Tags.Blocks.tag("storage_blocks/slime");
        public static final TagKey<Block> STORAGE_BLOCKS_WHEAT = Tags.Blocks.tag("storage_blocks/wheat");
        public static final TagKey<Block> OVERWORLD_NATURAL_LOGS = Tags.Blocks.tag("natural_logs/overworld");
        public static final TagKey<Block> NETHER_NATURAL_LOGS = Tags.Blocks.tag("natural_logs/nether");
        public static final TagKey<Block> NATURAL_LOGS = Tags.Blocks.tag("natural_logs");
        public static final TagKey<Block> NATURAL_WOODS = Tags.Blocks.tag("natural_woods");
        public static final TagKey<Block> STRIPPED_LOGS = Tags.Blocks.tag("stripped_logs");
        public static final TagKey<Block> STRIPPED_WOODS = Tags.Blocks.tag("stripped_woods");
        public static final TagKey<Block> VILLAGER_JOB_SITES = Tags.Blocks.tag("villager_job_sites");

        private static TagKey<Block> tag(String name) {
            return TagKey.create(Registries.BLOCK, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class EntityTypes {
        public static final TagKey<EntityType<?>> BOSSES = Tags.EntityTypes.tag("bosses");
        public static final TagKey<EntityType<?>> MINECARTS = Tags.EntityTypes.tag("minecarts");
        public static final TagKey<EntityType<?>> BOATS = Tags.EntityTypes.tag("boats");
        public static final TagKey<EntityType<?>> ITEM_FRAMES = Tags.EntityTypes.tag("item_frames");
        public static final TagKey<EntityType<?>> CAPTURING_NOT_SUPPORTED = Tags.EntityTypes.tag("capturing_not_supported");
        public static final TagKey<EntityType<?>> TELEPORTING_NOT_SUPPORTED = Tags.EntityTypes.tag("teleporting_not_supported");

        private static TagKey<EntityType<?>> tag(String name) {
            return TagKey.create(Registries.ENTITY_TYPE, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class Items {
        public static final TagKey<Item> BARRELS = Tags.Items.tag("barrels");
        public static final TagKey<Item> BARRELS_WOODEN = Tags.Items.tag("barrels/wooden");
        public static final TagKey<Item> BONES = Tags.Items.tag("bones");
        public static final TagKey<Item> BOOKSHELVES = Tags.Items.tag("bookshelves");
        public static final TagKey<Item> BRICKS = Tags.Items.tag("bricks");
        public static final TagKey<Item> BRICKS_NORMAL = Tags.Items.tag("bricks/normal");
        public static final TagKey<Item> BRICKS_NETHER = Tags.Items.tag("bricks/nether");
        public static final TagKey<Item> BRICKS_RESIN = Tags.Items.tag("bricks/resin");
        public static final TagKey<Item> BUCKETS = Tags.Items.tag("buckets");
        public static final TagKey<Item> BUCKETS_EMPTY = Tags.Items.tag("buckets/empty");
        public static final TagKey<Item> BUCKETS_WATER = Tags.Items.tag("buckets/water");
        public static final TagKey<Item> BUCKETS_LAVA = Tags.Items.tag("buckets/lava");
        public static final TagKey<Item> BUCKETS_MILK = Tags.Items.tag("buckets/milk");
        public static final TagKey<Item> BUCKETS_POWDER_SNOW = Tags.Items.tag("buckets/powder_snow");
        public static final TagKey<Item> BUCKETS_ENTITY_WATER = Tags.Items.tag("buckets/entity_water");
        public static final TagKey<Item> BUDDING_BLOCKS = Tags.Items.tag("budding_blocks");
        public static final TagKey<Item> BUDS = Tags.Items.tag("buds");
        public static final TagKey<Item> CHAINS = Tags.Items.tag("chains");
        public static final TagKey<Item> CHESTS = Tags.Items.tag("chests");
        public static final TagKey<Item> CHESTS_ENDER = Tags.Items.tag("chests/ender");
        public static final TagKey<Item> CHESTS_TRAPPED = Tags.Items.tag("chests/trapped");
        public static final TagKey<Item> CHESTS_WOODEN = Tags.Items.tag("chests/wooden");
        public static final TagKey<Item> COBBLESTONES = Tags.Items.tag("cobblestones");
        public static final TagKey<Item> COBBLESTONES_NORMAL = Tags.Items.tag("cobblestones/normal");
        public static final TagKey<Item> COBBLESTONES_INFESTED = Tags.Items.tag("cobblestones/infested");
        public static final TagKey<Item> COBBLESTONES_MOSSY = Tags.Items.tag("cobblestones/mossy");
        public static final TagKey<Item> COBBLESTONES_DEEPSLATE = Tags.Items.tag("cobblestones/deepslate");
        public static final TagKey<Item> CONCRETES = Tags.Items.tag("concretes");
        public static final TagKey<Item> CONCRETE_POWDERS = Tags.Items.tag("concrete_powders");
        public static final TagKey<Item> CLUSTERS = Tags.Items.tag("clusters");
        public static final TagKey<Item> CLUMPS = Tags.Items.tag("clumps");
        public static final TagKey<Item> CLUMPS_RESIN = Tags.Items.tag("clumps/resin");
        public static final TagKey<Item> CROPS = Tags.Items.tag("crops");
        public static final TagKey<Item> CROPS_BEETROOT = Tags.Items.tag("crops/beetroot");
        public static final TagKey<Item> CROPS_CACTUS = Tags.Items.tag("crops/cactus");
        public static final TagKey<Item> CROPS_CARROT = Tags.Items.tag("crops/carrot");
        public static final TagKey<Item> CROPS_COCOA_BEAN = Tags.Items.tag("crops/cocoa_bean");
        public static final TagKey<Item> CROPS_MELON = Tags.Items.tag("crops/melon");
        public static final TagKey<Item> CROPS_NETHER_WART = Tags.Items.tag("crops/nether_wart");
        public static final TagKey<Item> CROPS_POTATO = Tags.Items.tag("crops/potato");
        public static final TagKey<Item> CROPS_PUMPKIN = Tags.Items.tag("crops/pumpkin");
        public static final TagKey<Item> CROPS_SUGAR_CANE = Tags.Items.tag("crops/sugar_cane");
        public static final TagKey<Item> CROPS_WHEAT = Tags.Items.tag("crops/wheat");
        public static final TagKey<Item> DRINKS = Tags.Items.tag("drinks");
        public static final TagKey<Item> DRINKS_WATER = Tags.Items.tag("drinks/water");
        public static final TagKey<Item> DRINKS_WATERY = Tags.Items.tag("drinks/watery");
        public static final TagKey<Item> DRINKS_MILK = Tags.Items.tag("drinks/milk");
        public static final TagKey<Item> DRINKS_HONEY = Tags.Items.tag("drinks/honey");
        public static final TagKey<Item> DRINKS_MAGIC = Tags.Items.tag("drinks/magic");
        public static final TagKey<Item> DRINKS_OMINOUS = Tags.Items.tag("drinks/ominous");
        public static final TagKey<Item> DRINKS_JUICE = Tags.Items.tag("drinks/juice");
        public static final TagKey<Item> DRINK_CONTAINING_BOTTLE = Tags.Items.tag("drink_containing/bottle");
        public static final TagKey<Item> DRINK_CONTAINING_BUCKET = Tags.Items.tag("drink_containing/bucket");
        public static final TagKey<Item> DUSTS = Tags.Items.tag("dusts");
        public static final TagKey<Item> DUSTS_REDSTONE = Tags.Items.tag("dusts/redstone");
        public static final TagKey<Item> DUSTS_GLOWSTONE = Tags.Items.tag("dusts/glowstone");
        public static final TagKey<Item> DYED = Tags.Items.tag("dyed");
        public static final TagKey<Item> DYED_BLACK = Tags.Items.tag("dyed/black");
        public static final TagKey<Item> DYED_BLUE = Tags.Items.tag("dyed/blue");
        public static final TagKey<Item> DYED_BROWN = Tags.Items.tag("dyed/brown");
        public static final TagKey<Item> DYED_CYAN = Tags.Items.tag("dyed/cyan");
        public static final TagKey<Item> DYED_GRAY = Tags.Items.tag("dyed/gray");
        public static final TagKey<Item> DYED_GREEN = Tags.Items.tag("dyed/green");
        public static final TagKey<Item> DYED_LIGHT_BLUE = Tags.Items.tag("dyed/light_blue");
        public static final TagKey<Item> DYED_LIGHT_GRAY = Tags.Items.tag("dyed/light_gray");
        public static final TagKey<Item> DYED_LIME = Tags.Items.tag("dyed/lime");
        public static final TagKey<Item> DYED_MAGENTA = Tags.Items.tag("dyed/magenta");
        public static final TagKey<Item> DYED_ORANGE = Tags.Items.tag("dyed/orange");
        public static final TagKey<Item> DYED_PINK = Tags.Items.tag("dyed/pink");
        public static final TagKey<Item> DYED_PURPLE = Tags.Items.tag("dyed/purple");
        public static final TagKey<Item> DYED_RED = Tags.Items.tag("dyed/red");
        public static final TagKey<Item> DYED_WHITE = Tags.Items.tag("dyed/white");
        public static final TagKey<Item> DYED_YELLOW = Tags.Items.tag("dyed/yellow");
        public static final TagKey<Item> DYES = Tags.Items.tag("dyes");
        public static final TagKey<Item> DYES_BLACK = Tags.Items.tag("dyes/black");
        public static final TagKey<Item> DYES_RED = Tags.Items.tag("dyes/red");
        public static final TagKey<Item> DYES_GREEN = Tags.Items.tag("dyes/green");
        public static final TagKey<Item> DYES_BROWN = Tags.Items.tag("dyes/brown");
        public static final TagKey<Item> DYES_BLUE = Tags.Items.tag("dyes/blue");
        public static final TagKey<Item> DYES_PURPLE = Tags.Items.tag("dyes/purple");
        public static final TagKey<Item> DYES_CYAN = Tags.Items.tag("dyes/cyan");
        public static final TagKey<Item> DYES_LIGHT_GRAY = Tags.Items.tag("dyes/light_gray");
        public static final TagKey<Item> DYES_GRAY = Tags.Items.tag("dyes/gray");
        public static final TagKey<Item> DYES_PINK = Tags.Items.tag("dyes/pink");
        public static final TagKey<Item> DYES_LIME = Tags.Items.tag("dyes/lime");
        public static final TagKey<Item> DYES_YELLOW = Tags.Items.tag("dyes/yellow");
        public static final TagKey<Item> DYES_LIGHT_BLUE = Tags.Items.tag("dyes/light_blue");
        public static final TagKey<Item> DYES_MAGENTA = Tags.Items.tag("dyes/magenta");
        public static final TagKey<Item> DYES_ORANGE = Tags.Items.tag("dyes/orange");
        public static final TagKey<Item> DYES_WHITE = Tags.Items.tag("dyes/white");
        public static final TagKey<Item> EGGS = Tags.Items.tag("eggs");
        public static final TagKey<Item> END_STONES = Tags.Items.tag("end_stones");
        public static final TagKey<Item> ENDER_PEARLS = Tags.Items.tag("ender_pearls");
        public static final TagKey<Item> FEATHERS = Tags.Items.tag("feathers");
        public static final TagKey<Item> FENCE_GATES = Tags.Items.tag("fence_gates");
        public static final TagKey<Item> FENCE_GATES_WOODEN = Tags.Items.tag("fence_gates/wooden");
        public static final TagKey<Item> FENCES = Tags.Items.tag("fences");
        public static final TagKey<Item> FENCES_NETHER_BRICK = Tags.Items.tag("fences/nether_brick");
        public static final TagKey<Item> FENCES_WOODEN = Tags.Items.tag("fences/wooden");
        public static final TagKey<Item> FERTILIZERS = Tags.Items.tag("fertilizers");
        public static final TagKey<Item> FLOWERS_SMALL = Tags.Items.tag("flowers/small");
        public static final TagKey<Item> FLOWERS_TALL = Tags.Items.tag("flowers/tall");
        public static final TagKey<Item> FLOWERS = Tags.Items.tag("flowers");
        public static final TagKey<Item> FOODS = Tags.Items.tag("foods");
        public static final TagKey<Item> FOODS_FRUIT = Tags.Items.tag("foods/fruit");
        public static final TagKey<Item> FOODS_VEGETABLE = Tags.Items.tag("foods/vegetable");
        public static final TagKey<Item> FOODS_BERRY = Tags.Items.tag("foods/berry");
        public static final TagKey<Item> FOODS_BREAD = Tags.Items.tag("foods/bread");
        public static final TagKey<Item> FOODS_COOKIE = Tags.Items.tag("foods/cookie");
        public static final TagKey<Item> FOODS_DOUGH = Tags.Items.tag("foods/dough");
        public static final TagKey<Item> FOODS_RAW_MEAT = Tags.Items.tag("foods/raw_meat");
        public static final TagKey<Item> FOODS_COOKED_MEAT = Tags.Items.tag("foods/cooked_meat");
        public static final TagKey<Item> FOODS_RAW_FISH = Tags.Items.tag("foods/raw_fish");
        public static final TagKey<Item> FOODS_COOKED_FISH = Tags.Items.tag("foods/cooked_fish");
        public static final TagKey<Item> FOODS_SOUP = Tags.Items.tag("foods/soup");
        public static final TagKey<Item> FOODS_CANDY = Tags.Items.tag("foods/candy");
        public static final TagKey<Item> FOODS_PIE = Tags.Items.tag("foods/pie");
        public static final TagKey<Item> FOODS_GOLDEN = Tags.Items.tag("foods/golden");
        public static final TagKey<Item> FOODS_EDIBLE_WHEN_PLACED = Tags.Items.tag("foods/edible_when_placed");
        public static final TagKey<Item> FOODS_FOOD_POISONING = Tags.Items.tag("foods/food_poisoning");
        public static final TagKey<Item> ANIMAL_FOODS = Tags.Items.tag("animal_foods");
        public static final TagKey<Item> GEMS = Tags.Items.tag("gems");
        public static final TagKey<Item> GEMS_DIAMOND = Tags.Items.tag("gems/diamond");
        public static final TagKey<Item> GEMS_EMERALD = Tags.Items.tag("gems/emerald");
        public static final TagKey<Item> GEMS_AMETHYST = Tags.Items.tag("gems/amethyst");
        public static final TagKey<Item> GEMS_LAPIS = Tags.Items.tag("gems/lapis");
        public static final TagKey<Item> GEMS_PRISMARINE = Tags.Items.tag("gems/prismarine");
        public static final TagKey<Item> GEMS_QUARTZ = Tags.Items.tag("gems/quartz");
        public static final TagKey<Item> GLASS_BLOCKS = Tags.Items.tag("glass_blocks");
        public static final TagKey<Item> GLASS_BLOCKS_COLORLESS = Tags.Items.tag("glass_blocks/colorless");
        public static final TagKey<Item> GLASS_BLOCKS_CHEAP = Tags.Items.tag("glass_blocks/cheap");
        public static final TagKey<Item> GLASS_BLOCKS_TINTED = Tags.Items.tag("glass_blocks/tinted");
        public static final TagKey<Item> GLASS_PANES = Tags.Items.tag("glass_panes");
        public static final TagKey<Item> GLASS_PANES_COLORLESS = Tags.Items.tag("glass_panes/colorless");
        public static final TagKey<Item> GLAZED_TERRACOTTAS = Tags.Items.tag("glazed_terracottas");
        public static final TagKey<Item> GRAVELS = Tags.Items.tag("gravels");
        public static final TagKey<Item> GUNPOWDERS = Tags.Items.tag("gunpowders");
        public static final TagKey<Item> HIDDEN_FROM_RECIPE_VIEWERS = Tags.Items.tag("hidden_from_recipe_viewers");
        public static final TagKey<Item> INGOTS = Tags.Items.tag("ingots");
        public static final TagKey<Item> INGOTS_COPPER = Tags.Items.tag("ingots/copper");
        public static final TagKey<Item> INGOTS_GOLD = Tags.Items.tag("ingots/gold");
        public static final TagKey<Item> INGOTS_IRON = Tags.Items.tag("ingots/iron");
        public static final TagKey<Item> INGOTS_NETHERITE = Tags.Items.tag("ingots/netherite");
        public static final TagKey<Item> LEATHERS = Tags.Items.tag("leathers");
        public static final TagKey<Item> MUSHROOMS = Tags.Items.tag("mushrooms");
        public static final TagKey<Item> MUSIC_DISCS = Tags.Items.tag("music_discs");
        public static final TagKey<Item> NETHER_STARS = Tags.Items.tag("nether_stars");
        public static final TagKey<Item> NETHERRACKS = Tags.Items.tag("netherracks");
        public static final TagKey<Item> NUGGETS = Tags.Items.tag("nuggets");
        public static final TagKey<Item> NUGGETS_GOLD = Tags.Items.tag("nuggets/gold");
        public static final TagKey<Item> NUGGETS_IRON = Tags.Items.tag("nuggets/iron");
        public static final TagKey<Item> NUGGETS_COPPER = Tags.Items.tag("nuggets/copper");
        public static final TagKey<Item> OBSIDIANS = Tags.Items.tag("obsidians");
        public static final TagKey<Item> OBSIDIANS_NORMAL = Tags.Items.tag("obsidians/normal");
        public static final TagKey<Item> OBSIDIANS_CRYING = Tags.Items.tag("obsidians/crying");
        public static final TagKey<Item> ORE_BEARING_GROUND_DEEPSLATE = Tags.Items.tag("ore_bearing_ground/deepslate");
        public static final TagKey<Item> ORE_BEARING_GROUND_NETHERRACK = Tags.Items.tag("ore_bearing_ground/netherrack");
        public static final TagKey<Item> ORE_BEARING_GROUND_STONE = Tags.Items.tag("ore_bearing_ground/stone");
        public static final TagKey<Item> ORE_RATES_DENSE = Tags.Items.tag("ore_rates/dense");
        public static final TagKey<Item> ORE_RATES_SINGULAR = Tags.Items.tag("ore_rates/singular");
        public static final TagKey<Item> ORE_RATES_SPARSE = Tags.Items.tag("ore_rates/sparse");
        public static final TagKey<Item> ORES = Tags.Items.tag("ores");
        public static final TagKey<Item> ORES_COAL = Tags.Items.tag("ores/coal");
        public static final TagKey<Item> ORES_COPPER = Tags.Items.tag("ores/copper");
        public static final TagKey<Item> ORES_DIAMOND = Tags.Items.tag("ores/diamond");
        public static final TagKey<Item> ORES_EMERALD = Tags.Items.tag("ores/emerald");
        public static final TagKey<Item> ORES_GOLD = Tags.Items.tag("ores/gold");
        public static final TagKey<Item> ORES_IRON = Tags.Items.tag("ores/iron");
        public static final TagKey<Item> ORES_LAPIS = Tags.Items.tag("ores/lapis");
        public static final TagKey<Item> ORES_NETHERITE_SCRAP = Tags.Items.tag("ores/netherite_scrap");
        public static final TagKey<Item> ORES_QUARTZ = Tags.Items.tag("ores/quartz");
        public static final TagKey<Item> ORES_REDSTONE = Tags.Items.tag("ores/redstone");
        public static final TagKey<Item> ORES_IN_GROUND_DEEPSLATE = Tags.Items.tag("ores_in_ground/deepslate");
        public static final TagKey<Item> ORES_IN_GROUND_NETHERRACK = Tags.Items.tag("ores_in_ground/netherrack");
        public static final TagKey<Item> ORES_IN_GROUND_STONE = Tags.Items.tag("ores_in_ground/stone");
        public static final TagKey<Item> PLAYER_WORKSTATIONS_CRAFTING_TABLES = Tags.Items.tag("player_workstations/crafting_tables");
        public static final TagKey<Item> PLAYER_WORKSTATIONS_FURNACES = Tags.Items.tag("player_workstations/furnaces");
        public static final TagKey<Item> POTIONS = Tags.Items.tag("potions");
        public static final TagKey<Item> POTIONS_BOTTLE = Tags.Items.tag("potions/bottle");
        public static final TagKey<Item> PUMPKINS = Tags.Items.tag("pumpkins");
        public static final TagKey<Item> PUMPKINS_NORMAL = Tags.Items.tag("pumpkins/normal");
        public static final TagKey<Item> PUMPKINS_CARVED = Tags.Items.tag("pumpkins/carved");
        public static final TagKey<Item> PUMPKINS_JACK_O_LANTERNS = Tags.Items.tag("pumpkins/jack_o_lanterns");
        public static final TagKey<Item> RAW_MATERIALS = Tags.Items.tag("raw_materials");
        public static final TagKey<Item> RAW_MATERIALS_COPPER = Tags.Items.tag("raw_materials/copper");
        public static final TagKey<Item> RAW_MATERIALS_GOLD = Tags.Items.tag("raw_materials/gold");
        public static final TagKey<Item> RAW_MATERIALS_IRON = Tags.Items.tag("raw_materials/iron");
        public static final TagKey<Item> RODS = Tags.Items.tag("rods");
        public static final TagKey<Item> RODS_BLAZE = Tags.Items.tag("rods/blaze");
        public static final TagKey<Item> RODS_BREEZE = Tags.Items.tag("rods/breeze");
        public static final TagKey<Item> RODS_WOODEN = Tags.Items.tag("rods/wooden");
        public static final TagKey<Item> ROPES = Tags.Items.tag("ropes");
        public static final TagKey<Item> SANDS = Tags.Items.tag("sands");
        public static final TagKey<Item> SANDS_COLORLESS = Tags.Items.tag("sands/colorless");
        public static final TagKey<Item> SANDS_RED = Tags.Items.tag("sands/red");
        public static final TagKey<Item> SANDSTONE_BLOCKS = Tags.Items.tag("sandstone/blocks");
        public static final TagKey<Item> SANDSTONE_SLABS = Tags.Items.tag("sandstone/slabs");
        public static final TagKey<Item> SANDSTONE_STAIRS = Tags.Items.tag("sandstone/stairs");
        public static final TagKey<Item> SANDSTONE_RED_BLOCKS = Tags.Items.tag("sandstone/red_blocks");
        public static final TagKey<Item> SANDSTONE_RED_SLABS = Tags.Items.tag("sandstone/red_slabs");
        public static final TagKey<Item> SANDSTONE_RED_STAIRS = Tags.Items.tag("sandstone/red_stairs");
        public static final TagKey<Item> SANDSTONE_UNCOLORED_BLOCKS = Tags.Items.tag("sandstone/uncolored_blocks");
        public static final TagKey<Item> SANDSTONE_UNCOLORED_SLABS = Tags.Items.tag("sandstone/uncolored_slabs");
        public static final TagKey<Item> SANDSTONE_UNCOLORED_STAIRS = Tags.Items.tag("sandstone/uncolored_stairs");
        public static final TagKey<Item> SEEDS = Tags.Items.tag("seeds");
        public static final TagKey<Item> SEEDS_BEETROOT = Tags.Items.tag("seeds/beetroot");
        public static final TagKey<Item> SEEDS_MELON = Tags.Items.tag("seeds/melon");
        public static final TagKey<Item> SEEDS_PUMPKIN = Tags.Items.tag("seeds/pumpkin");
        public static final TagKey<Item> SEEDS_TORCHFLOWER = Tags.Items.tag("seeds/torchflower");
        public static final TagKey<Item> SEEDS_PITCHER_PLANT = Tags.Items.tag("seeds/pitcher_plant");
        public static final TagKey<Item> SEEDS_WHEAT = Tags.Items.tag("seeds/wheat");
        public static final TagKey<Item> SHULKER_BOXES = Tags.Items.tag("shulker_boxes");
        public static final TagKey<Item> SLIME_BALLS = Tags.Items.tag("slime_balls");
        public static final TagKey<Item> STONES = Tags.Items.tag("stones");
        public static final TagKey<Item> STORAGE_BLOCKS = Tags.Items.tag("storage_blocks");
        public static final TagKey<Item> STORAGE_BLOCKS_BONE_MEAL = Tags.Items.tag("storage_blocks/bone_meal");
        public static final TagKey<Item> STORAGE_BLOCKS_COAL = Tags.Items.tag("storage_blocks/coal");
        public static final TagKey<Item> STORAGE_BLOCKS_COPPER = Tags.Items.tag("storage_blocks/copper");
        public static final TagKey<Item> STORAGE_BLOCKS_DIAMOND = Tags.Items.tag("storage_blocks/diamond");
        public static final TagKey<Item> STORAGE_BLOCKS_DRIED_KELP = Tags.Items.tag("storage_blocks/dried_kelp");
        public static final TagKey<Item> STORAGE_BLOCKS_EMERALD = Tags.Items.tag("storage_blocks/emerald");
        public static final TagKey<Item> STORAGE_BLOCKS_GOLD = Tags.Items.tag("storage_blocks/gold");
        public static final TagKey<Item> STORAGE_BLOCKS_IRON = Tags.Items.tag("storage_blocks/iron");
        public static final TagKey<Item> STORAGE_BLOCKS_LAPIS = Tags.Items.tag("storage_blocks/lapis");
        public static final TagKey<Item> STORAGE_BLOCKS_NETHERITE = Tags.Items.tag("storage_blocks/netherite");
        public static final TagKey<Item> STORAGE_BLOCKS_RAW_COPPER = Tags.Items.tag("storage_blocks/raw_copper");
        public static final TagKey<Item> STORAGE_BLOCKS_RAW_GOLD = Tags.Items.tag("storage_blocks/raw_gold");
        public static final TagKey<Item> STORAGE_BLOCKS_RAW_IRON = Tags.Items.tag("storage_blocks/raw_iron");
        public static final TagKey<Item> STORAGE_BLOCKS_REDSTONE = Tags.Items.tag("storage_blocks/redstone");
        public static final TagKey<Item> STORAGE_BLOCKS_RESIN = Tags.Items.tag("storage_blocks/resin");
        public static final TagKey<Item> STORAGE_BLOCKS_SLIME = Tags.Items.tag("storage_blocks/slime");
        public static final TagKey<Item> STORAGE_BLOCKS_WHEAT = Tags.Items.tag("storage_blocks/wheat");
        public static final TagKey<Item> STRINGS = Tags.Items.tag("strings");
        public static final TagKey<Item> OVERWORLD_NATURAL_LOGS = Tags.Items.tag("natural_logs/overworld");
        public static final TagKey<Item> NETHER_NATURAL_LOGS = Tags.Items.tag("natural_logs/nether");
        public static final TagKey<Item> NATURAL_LOGS = Tags.Items.tag("natural_logs");
        public static final TagKey<Item> NATURAL_WOODS = Tags.Items.tag("natural_woods");
        public static final TagKey<Item> STRIPPED_LOGS = Tags.Items.tag("stripped_logs");
        public static final TagKey<Item> STRIPPED_WOODS = Tags.Items.tag("stripped_woods");
        public static final TagKey<Item> VILLAGER_JOB_SITES = Tags.Items.tag("villager_job_sites");
        public static final TagKey<Item> TOOLS = Tags.Items.tag("tools");
        public static final TagKey<Item> TOOLS_SHIELD = Tags.Items.tag("tools/shield");
        public static final TagKey<Item> TOOLS_BOW = Tags.Items.tag("tools/bow");
        public static final TagKey<Item> TOOLS_CROSSBOW = Tags.Items.tag("tools/crossbow");
        public static final TagKey<Item> TOOLS_FISHING_ROD = Tags.Items.tag("tools/fishing_rod");
        public static final TagKey<Item> TOOLS_TRIDENT = Tags.Items.tag("tools/trident");
        public static final TagKey<Item> TOOLS_SHEAR = Tags.Items.tag("tools/shear");
        public static final TagKey<Item> TOOLS_BRUSH = Tags.Items.tag("tools/brush");
        public static final TagKey<Item> TOOLS_IGNITER = Tags.Items.tag("tools/igniter");
        public static final TagKey<Item> TOOLS_MACE = Tags.Items.tag("tools/mace");
        public static final TagKey<Item> TOOLS_WRENCH = Tags.Items.tag("tools/wrench");
        public static final TagKey<Item> MELEE_WEAPON_TOOLS = Tags.Items.tag("tools/melee_weapon");
        public static final TagKey<Item> RANGED_WEAPON_TOOLS = Tags.Items.tag("tools/ranged_weapon");
        public static final TagKey<Item> MINING_TOOL_TOOLS = Tags.Items.tag("tools/mining_tool");
        public static final TagKey<Item> ARMORS = Tags.Items.tag("armors");
        public static final TagKey<Item> ARMORS_HUMANOID = Tags.Items.tag("armors/humanoid");
        public static final TagKey<Item> ARMORS_HORSE = Tags.Items.tag("armors/horse");
        public static final TagKey<Item> ARMORS_NAUTILUS = Tags.Items.tag("armors/nautilus");
        public static final TagKey<Item> ARMORS_WOLF = Tags.Items.tag("armors/wolf");
        public static final TagKey<Item> ENCHANTABLES = Tags.Items.tag("enchantables");

        private static TagKey<Item> tag(String name) {
            return TagKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class Fluids {
        public static final TagKey<Fluid> WATER = Tags.Fluids.tag("water");
        public static final TagKey<Fluid> LAVA = Tags.Fluids.tag("lava");
        public static final TagKey<Fluid> MILK = Tags.Fluids.tag("milk");
        public static final TagKey<Fluid> GASEOUS = Tags.Fluids.tag("gaseous");
        public static final TagKey<Fluid> HONEY = Tags.Fluids.tag("honey");
        public static final TagKey<Fluid> EXPERIENCE = Tags.Fluids.tag("experience");
        public static final TagKey<Fluid> POTION = Tags.Fluids.tag("potion");
        public static final TagKey<Fluid> SUSPICIOUS_STEW = Tags.Fluids.tag("suspicious_stew");
        public static final TagKey<Fluid> MUSHROOM_STEW = Tags.Fluids.tag("mushroom_stew");
        public static final TagKey<Fluid> RABBIT_STEW = Tags.Fluids.tag("rabbit_stew");
        public static final TagKey<Fluid> BEETROOT_SOUP = Tags.Fluids.tag("beetroot_soup");
        public static final TagKey<Fluid> HIDDEN_FROM_RECIPE_VIEWERS = Tags.Fluids.tag("hidden_from_recipe_viewers");

        private static TagKey<Fluid> tag(String name) {
            return TagKey.create(Registries.FLUID, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class Enchantments {
        public static final TagKey<Enchantment> INCREASE_BLOCK_DROPS = Tags.Enchantments.tag("increase_block_drops");
        public static final TagKey<Enchantment> INCREASE_ENTITY_DROPS = Tags.Enchantments.tag("increase_entity_drops");
        public static final TagKey<Enchantment> WEAPON_DAMAGE_ENHANCEMENTS = Tags.Enchantments.tag("weapon_damage_enhancements");
        public static final TagKey<Enchantment> ENTITY_SPEED_ENHANCEMENTS = Tags.Enchantments.tag("entity_speed_enhancements");
        public static final TagKey<Enchantment> ENTITY_AUXILIARY_MOVEMENT_ENHANCEMENTS = Tags.Enchantments.tag("entity_auxiliary_movement_enhancements");
        public static final TagKey<Enchantment> ENTITY_DEFENSE_ENHANCEMENTS = Tags.Enchantments.tag("entity_defense_enhancements");

        private static TagKey<Enchantment> tag(String name) {
            return TagKey.create(Registries.ENCHANTMENT, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class Biomes {
        public static final TagKey<Biome> NO_DEFAULT_MONSTERS = Tags.Biomes.tag("no_default_monsters");
        public static final TagKey<Biome> HIDDEN_FROM_LOCATOR_SELECTION = Tags.Biomes.tag("hidden_from_locator_selection");
        public static final TagKey<Biome> IS_VOID = Tags.Biomes.tag("is_void");
        public static final TagKey<Biome> IS_HOT = Tags.Biomes.tag("is_hot");
        public static final TagKey<Biome> IS_HOT_OVERWORLD = Tags.Biomes.tag("is_hot/overworld");
        public static final TagKey<Biome> IS_HOT_NETHER = Tags.Biomes.tag("is_hot/nether");
        public static final TagKey<Biome> IS_HOT_END = Tags.Biomes.tag("is_hot/end");
        public static final TagKey<Biome> IS_TEMPERATE = Tags.Biomes.tag("is_temperate");
        public static final TagKey<Biome> IS_TEMPERATE_OVERWORLD = Tags.Biomes.tag("is_temperate/overworld");
        public static final TagKey<Biome> IS_TEMPERATE_NETHER = Tags.Biomes.tag("is_temperate/nether");
        public static final TagKey<Biome> IS_TEMPERATE_END = Tags.Biomes.tag("is_temperate/end");
        public static final TagKey<Biome> IS_COLD = Tags.Biomes.tag("is_cold");
        public static final TagKey<Biome> IS_COLD_OVERWORLD = Tags.Biomes.tag("is_cold/overworld");
        public static final TagKey<Biome> IS_COLD_NETHER = Tags.Biomes.tag("is_cold/nether");
        public static final TagKey<Biome> IS_COLD_END = Tags.Biomes.tag("is_cold/end");
        public static final TagKey<Biome> IS_SPARSE_VEGETATION = Tags.Biomes.tag("is_sparse_vegetation");
        public static final TagKey<Biome> IS_SPARSE_VEGETATION_OVERWORLD = Tags.Biomes.tag("is_sparse_vegetation/overworld");
        public static final TagKey<Biome> IS_SPARSE_VEGETATION_NETHER = Tags.Biomes.tag("is_sparse_vegetation/nether");
        public static final TagKey<Biome> IS_SPARSE_VEGETATION_END = Tags.Biomes.tag("is_sparse_vegetation/end");
        public static final TagKey<Biome> IS_DENSE_VEGETATION = Tags.Biomes.tag("is_dense_vegetation");
        public static final TagKey<Biome> IS_DENSE_VEGETATION_OVERWORLD = Tags.Biomes.tag("is_dense_vegetation/overworld");
        public static final TagKey<Biome> IS_DENSE_VEGETATION_NETHER = Tags.Biomes.tag("is_dense_vegetation/nether");
        public static final TagKey<Biome> IS_DENSE_VEGETATION_END = Tags.Biomes.tag("is_dense_vegetation/end");
        public static final TagKey<Biome> IS_WET = Tags.Biomes.tag("is_wet");
        public static final TagKey<Biome> IS_WET_OVERWORLD = Tags.Biomes.tag("is_wet/overworld");
        public static final TagKey<Biome> IS_WET_NETHER = Tags.Biomes.tag("is_wet/nether");
        public static final TagKey<Biome> IS_WET_END = Tags.Biomes.tag("is_wet/end");
        public static final TagKey<Biome> IS_DRY = Tags.Biomes.tag("is_dry");
        public static final TagKey<Biome> IS_DRY_OVERWORLD = Tags.Biomes.tag("is_dry/overworld");
        public static final TagKey<Biome> IS_DRY_NETHER = Tags.Biomes.tag("is_dry/nether");
        public static final TagKey<Biome> IS_DRY_END = Tags.Biomes.tag("is_dry/end");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE = Tags.Biomes.tag("primary_wood_type");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_OAK = Tags.Biomes.tag("primary_wood_type/oak");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_BIRCH = Tags.Biomes.tag("primary_wood_type/birch");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_SPRUCE = Tags.Biomes.tag("primary_wood_type/spruce");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_JUNGLE = Tags.Biomes.tag("primary_wood_type/jungle");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_ACACIA = Tags.Biomes.tag("primary_wood_type/acacia");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_DARK_OAK = Tags.Biomes.tag("primary_wood_type/dark_oak");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_MANGROVE = Tags.Biomes.tag("primary_wood_type/mangrove");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_CHERRY = Tags.Biomes.tag("primary_wood_type/cherry");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_PALE_OAK = Tags.Biomes.tag("primary_wood_type/pale_oak");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_BAMBOO = Tags.Biomes.tag("primary_wood_type/bamboo");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_CRIMSON = Tags.Biomes.tag("primary_wood_type/crimson");
        public static final TagKey<Biome> PRIMARY_WOOD_TYPE_WARPED = Tags.Biomes.tag("primary_wood_type/warped");
        public static final TagKey<Biome> IS_OVERWORLD = Tags.Biomes.tag("is_overworld");
        public static final TagKey<Biome> IS_CONIFEROUS_TREE = Tags.Biomes.tag("is_tree/coniferous");
        public static final TagKey<Biome> IS_SAVANNA_TREE = Tags.Biomes.tag("is_tree/savanna");
        public static final TagKey<Biome> IS_JUNGLE_TREE = Tags.Biomes.tag("is_tree/jungle");
        public static final TagKey<Biome> IS_DECIDUOUS_TREE = Tags.Biomes.tag("is_tree/deciduous");
        public static final TagKey<Biome> IS_MOUNTAIN = Tags.Biomes.tag("is_mountain");
        public static final TagKey<Biome> IS_MOUNTAIN_PEAK = Tags.Biomes.tag("is_mountain/peak");
        public static final TagKey<Biome> IS_MOUNTAIN_SLOPE = Tags.Biomes.tag("is_mountain/slope");
        public static final TagKey<Biome> IS_PLAINS = Tags.Biomes.tag("is_plains");
        public static final TagKey<Biome> IS_SNOWY_PLAINS = Tags.Biomes.tag("is_snowy_plains");
        public static final TagKey<Biome> IS_FOREST = Tags.Biomes.tag("is_forest");
        public static final TagKey<Biome> IS_BIRCH_FOREST = Tags.Biomes.tag("is_birch_forest");
        public static final TagKey<Biome> IS_DARK_FOREST = Tags.Biomes.tag("is_dark_forest");
        public static final TagKey<Biome> IS_FLOWER_FOREST = Tags.Biomes.tag("is_flower_forest");
        public static final TagKey<Biome> IS_TAIGA = Tags.Biomes.tag("is_taiga");
        public static final TagKey<Biome> IS_OLD_GROWTH = Tags.Biomes.tag("is_old_growth");
        public static final TagKey<Biome> IS_HILL = Tags.Biomes.tag("is_hill");
        public static final TagKey<Biome> IS_WINDSWEPT = Tags.Biomes.tag("is_windswept");
        public static final TagKey<Biome> IS_JUNGLE = Tags.Biomes.tag("is_jungle");
        public static final TagKey<Biome> IS_SAVANNA = Tags.Biomes.tag("is_savanna");
        public static final TagKey<Biome> IS_SWAMP = Tags.Biomes.tag("is_swamp");
        public static final TagKey<Biome> IS_DESERT = Tags.Biomes.tag("is_desert");
        public static final TagKey<Biome> IS_BADLANDS = Tags.Biomes.tag("is_badlands");
        public static final TagKey<Biome> IS_BEACH = Tags.Biomes.tag("is_beach");
        public static final TagKey<Biome> IS_STONY_SHORES = Tags.Biomes.tag("is_stony_shores");
        public static final TagKey<Biome> IS_MUSHROOM = Tags.Biomes.tag("is_mushroom");
        public static final TagKey<Biome> IS_RIVER = Tags.Biomes.tag("is_river");
        public static final TagKey<Biome> IS_OCEAN = Tags.Biomes.tag("is_ocean");
        public static final TagKey<Biome> IS_DEEP_OCEAN = Tags.Biomes.tag("is_deep_ocean");
        public static final TagKey<Biome> IS_SHALLOW_OCEAN = Tags.Biomes.tag("is_shallow_ocean");
        public static final TagKey<Biome> IS_UNDERGROUND = Tags.Biomes.tag("is_underground");
        public static final TagKey<Biome> IS_CAVE = Tags.Biomes.tag("is_cave");
        public static final TagKey<Biome> IS_LUSH = Tags.Biomes.tag("is_lush");
        public static final TagKey<Biome> IS_MAGICAL = Tags.Biomes.tag("is_magical");
        public static final TagKey<Biome> IS_RARE = Tags.Biomes.tag("is_rare");
        public static final TagKey<Biome> IS_PLATEAU = Tags.Biomes.tag("is_plateau");
        public static final TagKey<Biome> IS_SPOOKY = Tags.Biomes.tag("is_spooky");
        public static final TagKey<Biome> IS_WASTELAND = Tags.Biomes.tag("is_wasteland");
        public static final TagKey<Biome> IS_DEAD = Tags.Biomes.tag("is_dead");
        public static final TagKey<Biome> IS_FLORAL = Tags.Biomes.tag("is_floral");
        public static final TagKey<Biome> IS_SANDY = Tags.Biomes.tag("is_sandy");
        public static final TagKey<Biome> IS_SNOWY = Tags.Biomes.tag("is_snowy");
        public static final TagKey<Biome> IS_ICY = Tags.Biomes.tag("is_icy");
        public static final TagKey<Biome> IS_AQUATIC = Tags.Biomes.tag("is_aquatic");
        public static final TagKey<Biome> IS_AQUATIC_ICY = Tags.Biomes.tag("is_aquatic_icy");
        public static final TagKey<Biome> IS_NETHER = Tags.Biomes.tag("is_nether");
        public static final TagKey<Biome> IS_NETHER_FOREST = Tags.Biomes.tag("is_nether_forest");
        public static final TagKey<Biome> IS_END = Tags.Biomes.tag("is_end");
        public static final TagKey<Biome> IS_OUTER_END_ISLAND = Tags.Biomes.tag("is_outer_end_island");

        private static TagKey<Biome> tag(String name) {
            return TagKey.create(Registries.BIOME, Identifier.fromNamespaceAndPath("c", name));
        }
    }

    public static final class Structures {
        public static final TagKey<Structure> HIDDEN_FROM_DISPLAYERS = Tags.Structures.tag("hidden_from_displayers");
        public static final TagKey<Structure> HIDDEN_FROM_LOCATOR_SELECTION = Tags.Structures.tag("hidden_from_locator_selection");

        private static TagKey<Structure> tag(String name) {
            return TagKey.create(Registries.STRUCTURE, Identifier.fromNamespaceAndPath("c", name));
        }
    }
}