package willatendo.simplelibrary.server.block;

import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;
import willatendo.simplelibrary.server.util.SimpleUtils;
import willatendo.simplelibrary.server.util.TagRegister;

public class ForgeBlockTags {
	public static final TagRegister<Block> BLOCKS = SimpleUtils.create(Registries.BLOCK, SimpleUtils.FORGE);

	public static final TagKey<Block> BARRELS = BLOCKS.register("barrels");
	public static final TagKey<Block> BARRELS_WOODEN = BLOCKS.register("barrels/wooden");
	public static final TagKey<Block> BOOKSHELVES = BLOCKS.register("bookshelves");
	public static final TagKey<Block> CHESTS = BLOCKS.register("chests");
	public static final TagKey<Block> CHESTS_ENDER = BLOCKS.register("chests/ender");
	public static final TagKey<Block> CHESTS_TRAPPED = BLOCKS.register("chests/trapped");
	public static final TagKey<Block> CHESTS_WOODEN = BLOCKS.register("chests/wooden");
	public static final TagKey<Block> COBBLESTONE = BLOCKS.register("cobblestone");
	public static final TagKey<Block> COBBLESTONE_NORMAL = BLOCKS.register("cobblestone/normal");
	public static final TagKey<Block> COBBLESTONE_INFESTED = BLOCKS.register("cobblestone/infested");
	public static final TagKey<Block> COBBLESTONE_MOSSY = BLOCKS.register("cobblestone/mossy");
	public static final TagKey<Block> COBBLESTONE_DEEPSLATE = BLOCKS.register("cobblestone/deepslate");
	public static final TagKey<Block> END_STONES = BLOCKS.register("end_stones");
	public static final TagKey<Block> ENDERMAN_PLACE_ON_BLACKLIST = BLOCKS.register("enderman_place_on_blacklist");
	public static final TagKey<Block> FENCE_GATES = BLOCKS.register("fence_gates");
	public static final TagKey<Block> FENCE_GATES_WOODEN = BLOCKS.register("fence_gates/wooden");
	public static final TagKey<Block> FENCES = BLOCKS.register("fences");
	public static final TagKey<Block> FENCES_NETHER_BRICK = BLOCKS.register("fences/nether_brick");
	public static final TagKey<Block> FENCES_WOODEN = BLOCKS.register("fences/wooden");
	public static final TagKey<Block> GLASS = BLOCKS.register("glass");
	public static final TagKey<Block> GLASS_BLACK = BLOCKS.register("glass/black");
	public static final TagKey<Block> GLASS_BLUE = BLOCKS.register("glass/blue");
	public static final TagKey<Block> GLASS_BROWN = BLOCKS.register("glass/brown");
	public static final TagKey<Block> GLASS_COLORLESS = BLOCKS.register("glass/colorless");
	public static final TagKey<Block> GLASS_CYAN = BLOCKS.register("glass/cyan");
	public static final TagKey<Block> GLASS_GRAY = BLOCKS.register("glass/gray");
	public static final TagKey<Block> GLASS_GREEN = BLOCKS.register("glass/green");
	public static final TagKey<Block> GLASS_LIGHT_BLUE = BLOCKS.register("glass/light_blue");
	public static final TagKey<Block> GLASS_LIGHT_GRAY = BLOCKS.register("glass/light_gray");
	public static final TagKey<Block> GLASS_LIME = BLOCKS.register("glass/lime");
	public static final TagKey<Block> GLASS_MAGENTA = BLOCKS.register("glass/magenta");
	public static final TagKey<Block> GLASS_ORANGE = BLOCKS.register("glass/orange");
	public static final TagKey<Block> GLASS_PINK = BLOCKS.register("glass/pink");
	public static final TagKey<Block> GLASS_PURPLE = BLOCKS.register("glass/purple");
	public static final TagKey<Block> GLASS_RED = BLOCKS.register("glass/red");
	public static final TagKey<Block> GLASS_SILICA = BLOCKS.register("glass/silica");
	public static final TagKey<Block> GLASS_TINTED = BLOCKS.register("glass/tinted");
	public static final TagKey<Block> GLASS_WHITE = BLOCKS.register("glass/white");
	public static final TagKey<Block> GLASS_YELLOW = BLOCKS.register("glass/yellow");
	public static final TagKey<Block> GLASS_PANES = BLOCKS.register("glass_panes");
	public static final TagKey<Block> GLASS_PANES_BLACK = BLOCKS.register("glass_panes/black");
	public static final TagKey<Block> GLASS_PANES_BLUE = BLOCKS.register("glass_panes/blue");
	public static final TagKey<Block> GLASS_PANES_BROWN = BLOCKS.register("glass_panes/brown");
	public static final TagKey<Block> GLASS_PANES_COLORLESS = BLOCKS.register("glass_panes/colorless");
	public static final TagKey<Block> GLASS_PANES_CYAN = BLOCKS.register("glass_panes/cyan");
	public static final TagKey<Block> GLASS_PANES_GRAY = BLOCKS.register("glass_panes/gray");
	public static final TagKey<Block> GLASS_PANES_GREEN = BLOCKS.register("glass_panes/green");
	public static final TagKey<Block> GLASS_PANES_LIGHT_BLUE = BLOCKS.register("glass_panes/light_blue");
	public static final TagKey<Block> GLASS_PANES_LIGHT_GRAY = BLOCKS.register("glass_panes/light_gray");
	public static final TagKey<Block> GLASS_PANES_LIME = BLOCKS.register("glass_panes/lime");
	public static final TagKey<Block> GLASS_PANES_MAGENTA = BLOCKS.register("glass_panes/magenta");
	public static final TagKey<Block> GLASS_PANES_ORANGE = BLOCKS.register("glass_panes/orange");
	public static final TagKey<Block> GLASS_PANES_PINK = BLOCKS.register("glass_panes/pink");
	public static final TagKey<Block> GLASS_PANES_PURPLE = BLOCKS.register("glass_panes/purple");
	public static final TagKey<Block> GLASS_PANES_RED = BLOCKS.register("glass_panes/red");
	public static final TagKey<Block> GLASS_PANES_WHITE = BLOCKS.register("glass_panes/white");
	public static final TagKey<Block> GLASS_PANES_YELLOW = BLOCKS.register("glass_panes/yellow");
	public static final TagKey<Block> GRAVEL = BLOCKS.register("gravel");
	public static final TagKey<Block> NETHERRACK = BLOCKS.register("netherrack");
	public static final TagKey<Block> OBSIDIAN = BLOCKS.register("obsidian");
	public static final TagKey<Block> ORE_BEARING_GROUND_DEEPSLATE = BLOCKS.register("ore_bearing_ground/deepslate");
	public static final TagKey<Block> ORE_BEARING_GROUND_NETHERRACK = BLOCKS.register("ore_bearing_ground/netherrack");
	public static final TagKey<Block> ORE_BEARING_GROUND_STONE = BLOCKS.register("ore_bearing_ground/stone");
	public static final TagKey<Block> ORE_RATES_DENSE = BLOCKS.register("ore_rates/dense");
	public static final TagKey<Block> ORE_RATES_SINGULAR = BLOCKS.register("ore_rates/singular");
	public static final TagKey<Block> ORE_RATES_SPARSE = BLOCKS.register("ore_rates/sparse");
	public static final TagKey<Block> ORES = BLOCKS.register("ores");
	public static final TagKey<Block> ORES_COAL = BLOCKS.register("ores/coal");
	public static final TagKey<Block> ORES_COPPER = BLOCKS.register("ores/copper");
	public static final TagKey<Block> ORES_DIAMOND = BLOCKS.register("ores/diamond");
	public static final TagKey<Block> ORES_EMERALD = BLOCKS.register("ores/emerald");
	public static final TagKey<Block> ORES_GOLD = BLOCKS.register("ores/gold");
	public static final TagKey<Block> ORES_IRON = BLOCKS.register("ores/iron");
	public static final TagKey<Block> ORES_LAPIS = BLOCKS.register("ores/lapis");
	public static final TagKey<Block> ORES_NETHERITE_SCRAP = BLOCKS.register("ores/netherite_scrap");
	public static final TagKey<Block> ORES_QUARTZ = BLOCKS.register("ores/quartz");
	public static final TagKey<Block> ORES_REDSTONE = BLOCKS.register("ores/redstone");
	public static final TagKey<Block> ORES_IN_GROUND_DEEPSLATE = BLOCKS.register("ores_in_ground/deepslate");
	public static final TagKey<Block> ORES_IN_GROUND_NETHERRACK = BLOCKS.register("ores_in_ground/netherrack");
	public static final TagKey<Block> ORES_IN_GROUND_STONE = BLOCKS.register("ores_in_ground/stone");
	public static final TagKey<Block> SAND = BLOCKS.register("sand");
	public static final TagKey<Block> SAND_COLORLESS = BLOCKS.register("sand/colorless");
	public static final TagKey<Block> SAND_RED = BLOCKS.register("sand/red");
	public static final TagKey<Block> SANDSTONE = BLOCKS.register("sandstone");
	public static final TagKey<Block> STAINED_GLASS = BLOCKS.register("stained_glass");
	public static final TagKey<Block> STAINED_GLASS_PANES = BLOCKS.register("stained_glass_panes");
	public static final TagKey<Block> STONE = BLOCKS.register("stone");
	public static final TagKey<Block> STORAGE_BLOCKS = BLOCKS.register("storage_blocks");
	public static final TagKey<Block> STORAGE_BLOCKS_AMETHYST = BLOCKS.register("storage_blocks/amethyst");
	public static final TagKey<Block> STORAGE_BLOCKS_COAL = BLOCKS.register("storage_blocks/coal");
	public static final TagKey<Block> STORAGE_BLOCKS_COPPER = BLOCKS.register("storage_blocks/copper");
	public static final TagKey<Block> STORAGE_BLOCKS_DIAMOND = BLOCKS.register("storage_blocks/diamond");
	public static final TagKey<Block> STORAGE_BLOCKS_EMERALD = BLOCKS.register("storage_blocks/emerald");
	public static final TagKey<Block> STORAGE_BLOCKS_GOLD = BLOCKS.register("storage_blocks/gold");
	public static final TagKey<Block> STORAGE_BLOCKS_IRON = BLOCKS.register("storage_blocks/iron");
	public static final TagKey<Block> STORAGE_BLOCKS_LAPIS = BLOCKS.register("storage_blocks/lapis");
	public static final TagKey<Block> STORAGE_BLOCKS_NETHERITE = BLOCKS.register("storage_blocks/netherite");
	public static final TagKey<Block> STORAGE_BLOCKS_QUARTZ = BLOCKS.register("storage_blocks/quartz");
	public static final TagKey<Block> STORAGE_BLOCKS_RAW_COPPER = BLOCKS.register("storage_blocks/raw_copper");
	public static final TagKey<Block> STORAGE_BLOCKS_RAW_GOLD = BLOCKS.register("storage_blocks/raw_gold");
	public static final TagKey<Block> STORAGE_BLOCKS_RAW_IRON = BLOCKS.register("storage_blocks/raw_iron");
	public static final TagKey<Block> STORAGE_BLOCKS_REDSTONE = BLOCKS.register("storage_blocks/redstone");
	public static final TagKey<Block> NEEDS_WOOD_TOOL = BLOCKS.register("needs_wood_tool");
	public static final TagKey<Block> NEEDS_GOLD_TOOL = BLOCKS.register("needs_gold_tool");
	public static final TagKey<Block> NEEDS_NETHERITE_TOOL = BLOCKS.register("needs_netherite_tool");
}
